import 'permission_keys.dart';

/// Derives a [Map<String, bool>] permission set from a role key.
///
/// This is the OFFLINE / COLD-START fallback used when:
///  - The app is launching for the first time (no Drift cache yet).
///  - Supabase is unreachable and the local cache is empty.
///
/// Once [PermissionService.loadPermissions] fetches the real per-employee
/// matrix from Supabase, this matrix is no longer consulted.
abstract final class DefaultPermissionMatrix {
  static Map<String, bool> forRole(String? roleKey) {
    return switch (roleKey?.toLowerCase().replaceAll(' ', '_')) {
      'super_admin' || 'owner' => _adminMatrix(),
      'branch_manager' => _branchManagerMatrix(),
      'cashier' => _cashierMatrix(),
      'inventory_staff' => _inventoryStaffMatrix(),
      _ => {},
    };
  }

  // ── Admin / Owner: unrestricted ──────────────────────────────────────────
  static Map<String, bool> _adminMatrix() => {
    for (final k in PermissionKeys.all) k: true,
  };

  // ── Branch Manager ───────────────────────────────────────────────────────
  static Map<String, bool> _branchManagerMatrix() => {
    PermissionKeys.posUse: true,
    PermissionKeys.posApplyDiscount: true,
    PermissionKeys.posVoidSale: true,
    PermissionKeys.posRefundSale: true,
    PermissionKeys.posApproveRefund: true,
    PermissionKeys.posOpenShift: true,
    PermissionKeys.posCloseShift: true,
    PermissionKeys.posViewOwnSales: true,
    PermissionKeys.posViewAllSales: true,
    PermissionKeys.productsView: true,
    PermissionKeys.productsCreate: true,
    PermissionKeys.productsEdit: true,
    PermissionKeys.productsDelete: false,
    PermissionKeys.productsManagePrices: true,
    PermissionKeys.productsManageCategories: true,
    PermissionKeys.inventoryView: true,
    PermissionKeys.inventoryAdjust: true,
    PermissionKeys.inventoryViewLevels: true,
    PermissionKeys.inventoryManageSuppliers: true,
    PermissionKeys.expensesView: true,
    PermissionKeys.expensesCreate: true,
    PermissionKeys.expensesApprove: true,
    PermissionKeys.expensesDelete: false,
    PermissionKeys.reportsViewOwn: true,
    PermissionKeys.reportsViewBranch: true,
    PermissionKeys.reportsViewAll: false,
    PermissionKeys.reportsExport: true,
    PermissionKeys.employeesView: true,
    PermissionKeys.employeesCreate: true,
    PermissionKeys.employeesEdit: true,
    PermissionKeys.employeesSuspend: true,
    PermissionKeys.employeesAssignRole: false,
    PermissionKeys.settingsView: true,
    PermissionKeys.settingsEditReceipt: true,
    PermissionKeys.settingsEditBusiness: false,
    PermissionKeys.settingsEditBranch: true,
    PermissionKeys.auditLogsView: false,
    PermissionKeys.suppliersView: true,
    PermissionKeys.suppliersManage: true,
    PermissionKeys.dashboardViewStats: true,
    PermissionKeys.dashboardViewBranchComparison: false,
    PermissionKeys.dashboardViewExpenses: true,
    PermissionKeys.dashboardViewLowStock: true,
    PermissionKeys.navPos: true,
    PermissionKeys.navInventory: true,
    PermissionKeys.navReports: true,
    PermissionKeys.navExpenses: true,
    PermissionKeys.navEmployees: true,
    PermissionKeys.navSettings: true,
    PermissionKeys.navAuditLogs: false,
    PermissionKeys.navSalesHistory: true,
    PermissionKeys.navSuppliers: true,
    PermissionKeys.dataCrossBranchAccess: false,
  };

  // ── Cashier ──────────────────────────────────────────────────────────────
  static Map<String, bool> _cashierMatrix() => {
    PermissionKeys.posUse: true,
    PermissionKeys.posApplyDiscount: true,
    PermissionKeys.posVoidSale: false,
    PermissionKeys.posRefundSale: true,
    PermissionKeys.posApproveRefund: false,
    PermissionKeys.posOpenShift: true,
    PermissionKeys.posCloseShift: true,
    PermissionKeys.posViewOwnSales: true,
    PermissionKeys.posViewAllSales: false,
    PermissionKeys.productsView: true,
    PermissionKeys.productsCreate: false,
    PermissionKeys.productsEdit: false,
    PermissionKeys.productsDelete: false,
    PermissionKeys.productsManagePrices: false,
    PermissionKeys.productsManageCategories: false,
    PermissionKeys.inventoryView: false,
    PermissionKeys.inventoryAdjust: false,
    PermissionKeys.inventoryViewLevels: false,
    PermissionKeys.inventoryManageSuppliers: false,
    PermissionKeys.expensesView: false,
    PermissionKeys.expensesCreate: false,
    PermissionKeys.expensesApprove: false,
    PermissionKeys.expensesDelete: false,
    PermissionKeys.reportsViewOwn: true,
    PermissionKeys.reportsViewBranch: false,
    PermissionKeys.reportsViewAll: false,
    PermissionKeys.reportsExport: false,
    PermissionKeys.employeesView: false,
    PermissionKeys.employeesCreate: false,
    PermissionKeys.employeesEdit: false,
    PermissionKeys.employeesSuspend: false,
    PermissionKeys.employeesAssignRole: false,
    PermissionKeys.settingsView: false,
    PermissionKeys.settingsEditReceipt: false,
    PermissionKeys.settingsEditBusiness: false,
    PermissionKeys.settingsEditBranch: false,
    PermissionKeys.auditLogsView: false,
    PermissionKeys.suppliersView: false,
    PermissionKeys.suppliersManage: false,
    PermissionKeys.dashboardViewStats: true,
    PermissionKeys.dashboardViewBranchComparison: false,
    PermissionKeys.dashboardViewExpenses: false,
    PermissionKeys.dashboardViewLowStock: false,
    PermissionKeys.navPos: true,
    PermissionKeys.navInventory: false,
    PermissionKeys.navReports: false,
    PermissionKeys.navExpenses: false,
    PermissionKeys.navEmployees: false,
    PermissionKeys.navSettings: false,
    PermissionKeys.navAuditLogs: false,
    PermissionKeys.navSalesHistory: false,
    PermissionKeys.navSuppliers: false,
    PermissionKeys.dataCrossBranchAccess: false,
  };

  // ── Inventory Staff ──────────────────────────────────────────────────────
  static Map<String, bool> _inventoryStaffMatrix() => {
    PermissionKeys.posUse: false,
    PermissionKeys.posApplyDiscount: false,
    PermissionKeys.posVoidSale: false,
    PermissionKeys.posRefundSale: false,
    PermissionKeys.posApproveRefund: false,
    PermissionKeys.posOpenShift: false,
    PermissionKeys.posCloseShift: false,
    PermissionKeys.posViewOwnSales: false,
    PermissionKeys.posViewAllSales: false,
    PermissionKeys.productsView: true,
    PermissionKeys.productsCreate: false,
    PermissionKeys.productsEdit: true,
    PermissionKeys.productsDelete: false,
    PermissionKeys.productsManagePrices: false,
    PermissionKeys.productsManageCategories: false,
    PermissionKeys.inventoryView: true,
    PermissionKeys.inventoryAdjust: true,
    PermissionKeys.inventoryViewLevels: true,
    PermissionKeys.inventoryManageSuppliers: true,
    PermissionKeys.expensesView: false,
    PermissionKeys.expensesCreate: false,
    PermissionKeys.expensesApprove: false,
    PermissionKeys.expensesDelete: false,
    PermissionKeys.reportsViewOwn: false,
    PermissionKeys.reportsViewBranch: false,
    PermissionKeys.reportsViewAll: false,
    PermissionKeys.reportsExport: false,
    PermissionKeys.employeesView: false,
    PermissionKeys.employeesCreate: false,
    PermissionKeys.employeesEdit: false,
    PermissionKeys.employeesSuspend: false,
    PermissionKeys.employeesAssignRole: false,
    PermissionKeys.settingsView: false,
    PermissionKeys.settingsEditReceipt: false,
    PermissionKeys.settingsEditBusiness: false,
    PermissionKeys.settingsEditBranch: false,
    PermissionKeys.auditLogsView: false,
    PermissionKeys.suppliersView: true,
    PermissionKeys.suppliersManage: true,
    PermissionKeys.dashboardViewStats: true,
    PermissionKeys.dashboardViewBranchComparison: false,
    PermissionKeys.dashboardViewExpenses: false,
    PermissionKeys.dashboardViewLowStock: true,
    PermissionKeys.navPos: false,
    PermissionKeys.navInventory: true,
    PermissionKeys.navReports: false,
    PermissionKeys.navExpenses: false,
    PermissionKeys.navEmployees: false,
    PermissionKeys.navSettings: false,
    PermissionKeys.navAuditLogs: false,
    PermissionKeys.navSalesHistory: false,
    PermissionKeys.navSuppliers: true,
    PermissionKeys.dataCrossBranchAccess: false,
  };
}
